
version: '3.7'

networks:
  easy_nginx:

services:
  service.dummy:
    container_name: service.dummy
    image: tommystark/dummy-node-app
    hostname: service.dummy
    networks:
      - easy_nginx
  nginx:
    depends_on:
      - service.dummy
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - easy_nginx
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
      - ${PWD}/nginx/ssl:/etc/nginx/ssl
      - ${PWD}/certs:/etc/letsencrypt
